@startuml bridge

/'
Gracz(4) ParaGraczy
Karta
Talia
Gra -> Rozgrywka
       Rozgrywka -> Lewa
       Licytacja
       Licytacja -> Odzywka
       Licytacja -> Kontrakt

Odzywka <--> Rozgrywka?

Reka (?)
Punktacja
'/


class Rozgrywka {}
class Licytacja {}
class Lewa {}
class Odzywka {}
class Kontrakt {}

Gracz "4" -right- "1" Gra : graja

Gra "1" - "1" Talia : uzywa

Talia "1 sklada sie z 52" --- "nalezy do" Karta 

Gra "1" -- "*" Tura : sklada sie z

Tura "1" -left- "1" Licytacja : zawiera
Tura "1" -- "1" Rozgrywka 
: zawiera

Licytacja "1" -- "*" Odzywka: sklada sie z 
Rozgrywka "1" -right- "0..*" Lewa : sklada sie z


Odzywka <-- Kontrakt
Rozgrywka -- Kontrakt : zawiera

ParaGraczy "1" -right- "2" Gracz : dobierani sa

Licytacja "1" --- "1" Kontrakt : konczy sie 

Gracz "1" -up- "1" Reka
Reka "1" -up- "0..13" Karta : zawiera

ParaGraczy ------ Lewa : wygrywa
Gracz --- Odzywka : zagrywa

/'
Gra -- Rozgrywka
Rozgrywka -- Lewa
Gra -- Licytacja
Licytacja -- Odzywka
Licytacja - Kontrakt
'/

@enduml bridge
